# Generated by Django 2.2.7 on 2019-12-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0002_auto_20191202_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcourses',
            name='startedfrom',
        ),
    ]
