# Generated by Django 2.2.7 on 2019-12-05 06:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0003_remove_allcourses_startedfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateField(default=datetime.datetime(2019, 12, 5, 6, 32, 15, 50181, tzinfo=utc), verbose_name='Started from'),
            preserve_default=False,
        ),
    ]
