# Generated by Django 2.2.7 on 2019-12-05 09:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0006_remove_allcourses_startedfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 9, 24, 37, 32600, tzinfo=utc), verbose_name='Started from'),
            preserve_default=False,
        ),
    ]
